version: '3.5'

services: 
    front-end:
        build: frontend-example-docker/
        ports: 
            - 5000:5000
    back-end:
        build: backend-example-docker/
        ports: 
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
    redis: 
        image: redis