FROM node:10.21.0

WORKDIR /mydir

COPY . .
RUN npm install
EXPOSE 8000

#This is due 1.12
ENV FRONT_URL="http://localhost:5000"

CMD ["npm", "start"]


#$ docker build -t backend-example .
#$ docker run --rm -it  -p 8000:8000/tcp backend-example
#$ docker run --rm -it  -p 8000:8000/tcp -v $(pwd)/logs.txt:/mydir/logs.txt backend-example