FROM node:10.21.0

WORKDIR /mydir

COPY . .
RUN npm install
EXPOSE 5000

#This is due 1.12
ENV API_URL="http://localhost:8000" 

CMD ["npm", "start"]

#$ docker build -t frontend-example .
#$ docker run -it -p 5000:5000 --rm frontend-example